name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for merge conflicts
        id: check-conflicts
        run: |
          if git merge-tree $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^<<<<<"; then
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
          else
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto Merge PR
        if: steps.check-conflicts.outputs.has_conflicts == 'false'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Auto-merge pull request #${pullRequestNumber}"
          MERGE_RETRY_SLEEP: "60000"
